# Streamlit Configuration for Better Performance
# This file reduces the gray overlay duration and improves app responsiveness

[runner]
# Make script reruns faster
fastReruns = true

# Reduce delay before showing running indicator (milliseconds)
scriptRunnerPollIntervalMs = 100

[server]
# Enable file watcher for faster updates
fileWatcherType = "auto"

# Run on save in faster mode  
runOnSave = true

# Max upload size (50MB)
maxUploadSize = 50

[client]
# Show error details for debugging
showErrorDetails = true

# Toolbar mode - minimal for cleaner UI
toolbarMode = "minimal"

[browser]
# Disable gathering usage stats (slightly faster)
gatherUsageStats = false

# Server address
serverAddress = "localhost"

[theme]
# You can customize theme here if needed
# primaryColor = "#FF6B6B"
# backgroundColor = "#0E1117"
# secondaryBackgroundColor = "#262730"
# textColor = "#FAFAFA"
